# Generated by Django 5.2 on 2025-04-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": ["name"]},
        ),
    ]
