# Generated by Django 5.2 on 2025-04-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_dish_options_alter_dishtype_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.DateField(),
        ),
    ]
