# Generated by Django 5.2 on 2025-04-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={"verbose_name": "cook", "verbose_name_plural": "cooks"},
        ),
        migrations.RenameField(
            model_name="dish",
            old_name="cook",
            new_name="cooks",
        ),
    ]
