# Generated by Django 5.2 on 2025-04-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_ingredient_dish_ingredients"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cook",
        ),
    ]
