# Generated by Django 5.2 on 2025-04-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
